// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olcsikepezbznfkynxwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sY3Npa2VwZXpiem5ma3lueHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Njk0MTMsImV4cCI6MjA2MzQ0NTQxM30.oY_Qj2do4xQSVNjOipXkmrPvIq0GtMOtG3wtpJAvbH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);